### ISSUE TITLE
Add Node Shutdown Status API

### ISSUE THREAD

**Issue by gwbrown** [elastic/support-diagnostics#536]
In 7.15.0, we're releasing the [Node Shutdown API](https://www.elastic.co/guide/en/elasticsearch/reference/7.15/node-lifecycle-api.html).

While this API is (currently) marked as Cloud-only in the docs and is intended only for operator use, the feature is enabled for on-prem deployments, and we'd like to make sure we have visibility here just in case.

Specifically, we'd like to collect the output of the [Get Shutdown Status API](https://www.elastic.co/guide/en/elasticsearch/reference/7.15/get-shutdown.html). I believe this will look like:
```yaml
node_shutdown_status:
  subdir: "commercial"
  versions:
    ">= 7.15.0": "/_nodes/shutdown?pretty"
```
